### ISSUE TITLE
fix: 배포 서버 DB timezone 버그

### ISSUE THREAD

**Issue by oeeen** [WoowaCrew/WoowaCrew#303]
게시글 업로드 하자마자 9시간 전이 됨. UTC-9 
<img width="997" alt="스크린샷 2020-02-02 오후 3 21 02" src="https://user-images.githubusercontent.com/16066456/73604179-b4aced00-45cf-11ea-9f11-54c1be5f2532.png">

**Comment by vsh123** [comment]
linux 시간 변경하였습니다
![image](https://user-images.githubusercontent.com/32254689/73649189-9aa00700-46c2-11ea-857e-5b7ec336c015.png)
