### ISSUE TITLE
feat: axios 통일

### ISSUE THREAD

**Issue by vsh123** [WoowaCrew/WoowaCrew#353]

**Comment by ttkmw** [comment]
안녕하세요, 우아한테크코스 2기 임루트입니다.
제가 예전에 했던 작업이랑 비슷한 것 같아서, 작업중이신 분이 없으면 제가 해봐도 될까요?
제가 했던 건 axios di 인데요, 관련된 글은 [여기](https://p-vibe.github.io/2019/08/04/axios-di)에 적어놨습니다.
위에는 수정 전일 거라 코드를 보시긴 어려울텐데요,
저 때 작업한 코드는 [여기](https://github.com/DE-labtory/hatchout-web)에서 보실 수 있습니다.

혹시 이 이슈가 vue에서 axios를 di하려고 하는 것이고, 하고 계신 분이 없고, 한번 맡겨보실 생각이 있으시면
slack에 임루트로 dm 주세요~
